version: '3.4'

services:
  newspagesclientapp:
    image: ${DOCKER_REGISTRY-}newspagesclientapp
    build:
      context: .
      dockerfile: NewsPagesClientApp\Dockerfile
    ports:
      - "7092:7092"
  AngularClient:
    image: ${DOCKER_REGISTRY-}angular-client
    build:
      context: .
      dockerfile: AngularClient/Dockerfile
    ports:
      - "4200:4200" 
  Pages:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Ivan
    ports:
      - "5432:5432"
